#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Agent Performance Analytics Dashboard

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

# Check if we're in the project root
if [ ! -d "auto-claude-ui" ]; then
    echo -e "${RED}Error: Must run from project root directory${NC}"
    exit 1
fi

# Check for node_modules
if [ ! -d "auto-claude-ui/node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    cd auto-claude-ui && npm install && cd ..
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Auto Claude UI..."
cd auto-claude-ui && npm run dev &
UI_PID=$!
cd ..

# Wait for Electron app to start (Vite dev server)
wait_for_service 3000 "Auto Claude UI"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Auto Claude UI: http://localhost:3000 (Electron app)"
echo ""
echo "Process IDs:"
echo "  UI: $UI_PID"
echo ""
echo "To stop services, run: kill $UI_PID"
echo ""
echo "Development Notes:"
echo "  - Changes to React components will hot-reload"
echo "  - Changes to main process require restart"
echo "  - View Analytics will be at: Sidebar > Analytics (Y shortcut)"
echo ""
